CREATE TABLE IF NOT EXISTS records (
  collection TEXT NOT NULL,
  id TEXT NOT NULL,
  body JSONB NOT NULL,
  position BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  PRIMARY KEY (collection, id)
);

CREATE INDEX IF NOT EXISTS records_collection_position_idx
  ON records (collection, position);
